### ISSUE TITLE
Some questions about the R-Frame booster

### ISSUE THREAD

**Issue by Kiyi-Lee** [sshao2013/ConvBoost#1]
Thanks for sharing the project; it's a great job. 
I have reviewed the paper and the code and have a few questions. 
Firstly, I am having trouble understanding the random offset Δ𝑘 ∈ [0, ⌊𝐿/2⌋] in the R-Frame booster, where 𝐿 represents the window/frame length. Could you please clarify what exactly the frame length is? Additionally, is the window referring to the window step? I noticed the code snippet that generates dynamic data, such as data_start = int(np.random.randint(low=0, high=self.args.win_step, size=1)), but I didn't see any operations related to calculating Δ𝑘 ∈ [0, ⌊𝐿/2⌋]. 
Secondly, I'm curious why resampling is performed by default with data_start = np.random.randint(low=0, high=x_train.shape[0], size=x_train.shape[0]). Why wasn't this included in the section that generates dynamic data? 
I'm eagerly awaiting your response. Your assistance is greatly appreciated.

**Comment by sshao2013** [comment]
To answer your first question about our data processing technique: We used a sliding window approach, segmenting the data into fixed-length frames. To exemplify, with OPP, each frame has 32 samples. Moreover, we've applied a 50% overlap between these frames. This means that while one frame has a length of 32 samples, the subsequent frame begins 16 samples into the current window. This overlap is denoted as L/2 in our paper. And for the r-framing method, you can choose any value between 0 to L/2 as your random offset.

As for your second question, it is related to bootstrapping as mentioned in the paper. For a deeper comprehension, I recommend consulting the paper 'Ensembles of Deep LSTM Learners for Activity Recognition using Wearables'.

I trust this provides clarity. Thank you.

**Comment by Kiyi-Lee** [comment]
Thanks for your reply. I misunderstood that the window/frame length was a division operation，it's actually an alternative name. Additionally, I didn't notice that self.args.win_step represents half of the window size. In the meantime, I will carefully review the recommended paper. Thank you.
